from PyQt4 import QtCore, QtGui


class DatabaseSettings(QtGui.QDialog):
    def __init__(self, parent=None):
        QtGui.QDialog.__init__(self, parent)
        self.setObjectName("Database Settings")
        self.resize(250, 111)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/appLogo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setWindowIcon(icon)
        self.gridLayout = QtGui.QGridLayout(self)
        self.label = QtGui.QLabel(self)
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.hostname = QtGui.QLineEdit(self)
        self.hostname.setObjectName("hostname")
        self.gridLayout.addWidget(self.hostname, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self)
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.database = QtGui.QLineEdit(self)
        self.database.setObjectName("database")
        self.gridLayout.addWidget(self.database, 1, 1, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(self)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel | QtGui.QDialogButtonBox.Ok)
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 2)

        self.retranslateUi(self)
        self.accepted.connect(self.accept)
        self.rejected.connect(self.reject)
        self.setTabOrder(self.hostname, self.database)
        self.setTabOrder(self.database, self.buttonBox)


class MainWindow(QtGui.QMainWindow):
    def __init__(self):
        QtGui.QMainWindow.__init__(self)
        self.setObjectName("Laser Schedule")
        self.resize(1024, 768)
        self.centralwidget = QtGui.QWidget(self)
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.setCentralWidget(self.centralwidget)


class NewRow(QtGui.QWidget):
    def __init__(self, parent=None):
        QtGui.QWidget.__init__(self, parent)
        self.setObjectName("New Row")
        self.resize(874, 77)
        self.setMaximumHeight(77)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.setFont(font)
        self.setMouseTracking(True)
        self.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.setStyleSheet("background-color: rgb(225, 225, 225); border-color: rgb(230, 230, 230);")
        self.verticalLayout = QtGui.QVBoxLayout(self)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setMargin(0)
        self.frame = QtGui.QFrame(self)
        self.frame.setMouseTracking(True)
        self.frame.setFocusPolicy(QtCore.Qt.NoFocus)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setLineWidth(1)
        self.gridLayout = QtGui.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(6, 4, 6, 5)
        self.gridLayout.setHorizontalSpacing(12)
        self.uploadPDF = QtGui.QPushButton(self.frame)
        self.uploadPDF.setMouseTracking(True)
        self.uploadPDF.setFocusPolicy(QtCore.Qt.NoFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/upload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uploadPDF.setIcon(icon)
        self.uploadPDF.setFlat(True)
        self.gridLayout.addWidget(self.uploadPDF, 0, 3, 2, 1)
        self.hideJob = QtGui.QPushButton(self.frame)
        self.hideJob.setMouseTracking(True)
        self.hideJob.setFocusPolicy(QtCore.Qt.NoFocus)
        self.hideJob.setAutoFillBackground(False)
        self.hideJob.setStyleSheet("background-color: rgb(255, 255, 255);border-width:0px;")
        self.gridLayout.addWidget(self.hideJob, 0, 7, 2, 1)
        self.editJob = QtGui.QPushButton(self.frame)
        self.editJob.setMouseTracking(True)
        self.editJob.setFocusPolicy(QtCore.Qt.NoFocus)
        self.editJob.setAutoFillBackground(False)
        self.editJob.setStyleSheet("background-color: rgb(255, 255, 255);border-width:0px;")
        self.gridLayout.addWidget(self.editJob, 0, 6, 2, 1)
        self.materialQty = QtGui.QLineEdit(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.materialQty.sizePolicy().hasHeightForWidth())
        self.materialQty.setSizePolicy(sizePolicy)
        self.materialQty.setMinimumSize(QtCore.QSize(50, 24))
        self.materialQty.setMaximumSize(QtCore.QSize(75, 24))
        self.materialQty.setMouseTracking(False)
        self.materialQty.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.materialQty.setStyleSheet("border-width:0px;")
        self.materialQty.setFrame(False)
        self.materialQty.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.materialQty.setObjectName("materialQty")
        self.gridLayout.addWidget(self.materialQty, 1, 5, 1, 1)
        self.jobNumber = QtGui.QLineEdit(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jobNumber.sizePolicy().hasHeightForWidth())
        self.jobNumber.setSizePolicy(sizePolicy)
        self.jobNumber.setMouseTracking(False)
        self.jobNumber.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.jobNumber.setStyleSheet("border-width:0px;")
        self.jobNumber.setFrame(False)
        self.jobNumber.setAlignment(QtCore.Qt.AlignCenter)
        self.gridLayout.addWidget(self.jobNumber, 0, 1, 2, 1)
        self.material = QtGui.QLineEdit(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.material.sizePolicy().hasHeightForWidth())
        self.material.setSizePolicy(sizePolicy)
        self.material.setMouseTracking(False)
        self.material.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.material.setStyleSheet("border-width:0px;")
        self.material.setFrame(False)
        self.material.setAlignment(QtCore.Qt.AlignCenter)
        self.gridLayout.addWidget(self.material, 0, 4, 1, 2)
        self.priority = QtGui.QLineEdit(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.priority.sizePolicy().hasHeightForWidth())
        self.priority.setSizePolicy(sizePolicy)
        self.priority.setMinimumSize(QtCore.QSize(75, 57))
        self.priority.setMaximumSize(QtCore.QSize(75, 57))
        self.priority.setMouseTracking(False)
        self.priority.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.priority.setStyleSheet("border-width:0px;")
        self.priority.setFrame(False)
        self.priority.setAlignment(QtCore.Qt.AlignCenter)
        self.gridLayout.addWidget(self.priority, 0, 0, 2, 1)
        self.printReport = QtGui.QPushButton(self.frame)
        self.printReport.setMouseTracking(True)
        self.printReport.setFocusPolicy(QtCore.Qt.NoFocus)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/printer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.printReport.setIcon(icon1)
        self.printReport.setFlat(True)
        self.gridLayout.addWidget(self.printReport, 0, 2, 2, 1)
        self.label = QtGui.QLabel(self.frame)
        self.label.setMouseTracking(True)
        self.label.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.gridLayout.addWidget(self.label, 1, 4, 1, 1)
        self.notes = QtGui.QPlainTextEdit(self.frame)
        self.notes.setMaximumSize(QtCore.QSize(16777215, 50))
        self.notes.setMouseTracking(True)
        self.notes.setFocusPolicy(QtCore.Qt.NoFocus)
        self.notes.setAutoFillBackground(True)
        self.notes.setStyleSheet("border-width:0px;background-color: rgb(255, 255, 255);")
        self.gridLayout.addWidget(self.notes, 0, 8, 2, 1)
        self.line = QtGui.QFrame(self.frame)
        self.line.setMouseTracking(True)
        self.line.setFocusPolicy(QtCore.Qt.NoFocus)
        self.line.setStyleSheet("color: rgb(255, 255, 255);")
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.gridLayout.addWidget(self.line, 2, 0, 1, 9)
        self.verticalLayout.addWidget(self.frame)


class Schedule(QtGui.QWidget):
    def __init__(self, parent=None):
        QtGui.QWidget.__init__(self, parent)
        self.setObjectName("Schedule")
        self.resize(931, 637)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/production.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setWindowIcon(icon)
        self.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.title = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Terminus")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.horizontalLayout.addWidget(self.title)
        spacerItem = QtGui.QSpacerItem(478, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.verticalLayout.addWidget(self.line)
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 919, 530))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setMargin(0)
        self.scheduleFrame = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scheduleFrame.sizePolicy().hasHeightForWidth())
        self.scheduleFrame.setSizePolicy(sizePolicy)
        self.scheduleFrame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.scheduleFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.scheduleFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.scheduleFrame)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_2.setContentsMargins(-1, 4, -1, 5)
        self.horizontalLayout_2.addWidget(self.scheduleFrame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout.addWidget(self.scrollArea)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.verticalLayout.setStretch(2, 1)
        self.setCentralWidget(self.centralwidget)